### Obtener todos los repartidores
GET http://localhost:3000/repartidor

### Obtener repartidor por ID
GET http://localhost:3000/repartidor/1

### Registrar repartidor
POST http://localhost:3000/repartidor
Content-Type: application/json

{
  "nombre": "Repartidor 1",
  "telefono": "999999999"
}

### Actualizar repartidor
PUT http://localhost:3000/repartidor/1
Content-Type: application/json

{
  "telefono": "988888888"
}

### Eliminar repartidor
DELETE http://localhost:3000/repartidor/1
